// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/post.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PostProto {
  public static partial class Post
  {
    static readonly string __ServiceName = "PostProto.Post";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::PostProto.NewPostInfo> __Marshaller_PostProto_NewPostInfo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PostProto.NewPostInfo.Parser));
    static readonly grpc::Marshaller<global::PostProto.CreateNewPostResult> __Marshaller_PostProto_CreateNewPostResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PostProto.CreateNewPostResult.Parser));
    static readonly grpc::Marshaller<global::PostProto.UpdateMemberPostShowList> __Marshaller_PostProto_UpdateMemberPostShowList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PostProto.UpdateMemberPostShowList.Parser));
    static readonly grpc::Marshaller<global::PostProto.UpdateShowListResult> __Marshaller_PostProto_UpdateShowListResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PostProto.UpdateShowListResult.Parser));

    static readonly grpc::Method<global::PostProto.NewPostInfo, global::PostProto.CreateNewPostResult> __Method_CreateNewPostFun = new grpc::Method<global::PostProto.NewPostInfo, global::PostProto.CreateNewPostResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateNewPostFun",
        __Marshaller_PostProto_NewPostInfo,
        __Marshaller_PostProto_CreateNewPostResult);

    static readonly grpc::Method<global::PostProto.UpdateMemberPostShowList, global::PostProto.UpdateShowListResult> __Method_UpdatePostShowListFun = new grpc::Method<global::PostProto.UpdateMemberPostShowList, global::PostProto.UpdateShowListResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdatePostShowListFun",
        __Marshaller_PostProto_UpdateMemberPostShowList,
        __Marshaller_PostProto_UpdateShowListResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PostProto.PostReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Post</summary>
    [grpc::BindServiceMethod(typeof(Post), "BindService")]
    public abstract partial class PostBase
    {
      public virtual global::System.Threading.Tasks.Task<global::PostProto.CreateNewPostResult> CreateNewPostFun(global::PostProto.NewPostInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::PostProto.UpdateShowListResult> UpdatePostShowListFun(global::PostProto.UpdateMemberPostShowList request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Post</summary>
    public partial class PostClient : grpc::ClientBase<PostClient>
    {
      /// <summary>Creates a new client for Post</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PostClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Post that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PostClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PostClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PostClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PostProto.CreateNewPostResult CreateNewPostFun(global::PostProto.NewPostInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateNewPostFun(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PostProto.CreateNewPostResult CreateNewPostFun(global::PostProto.NewPostInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateNewPostFun, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PostProto.CreateNewPostResult> CreateNewPostFunAsync(global::PostProto.NewPostInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateNewPostFunAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PostProto.CreateNewPostResult> CreateNewPostFunAsync(global::PostProto.NewPostInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateNewPostFun, null, options, request);
      }
      public virtual global::PostProto.UpdateShowListResult UpdatePostShowListFun(global::PostProto.UpdateMemberPostShowList request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePostShowListFun(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PostProto.UpdateShowListResult UpdatePostShowListFun(global::PostProto.UpdateMemberPostShowList request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdatePostShowListFun, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PostProto.UpdateShowListResult> UpdatePostShowListFunAsync(global::PostProto.UpdateMemberPostShowList request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePostShowListFunAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PostProto.UpdateShowListResult> UpdatePostShowListFunAsync(global::PostProto.UpdateMemberPostShowList request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdatePostShowListFun, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PostClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PostClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PostBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateNewPostFun, serviceImpl.CreateNewPostFun)
          .AddMethod(__Method_UpdatePostShowListFun, serviceImpl.UpdatePostShowListFun).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PostBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateNewPostFun, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PostProto.NewPostInfo, global::PostProto.CreateNewPostResult>(serviceImpl.CreateNewPostFun));
      serviceBinder.AddMethod(__Method_UpdatePostShowListFun, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PostProto.UpdateMemberPostShowList, global::PostProto.UpdateShowListResult>(serviceImpl.UpdatePostShowListFun));
    }

  }
}
#endregion
